### ISSUE TITLE
Stable Release?

### ISSUE THREAD

**Issue by hexfusion** [joyrex2001/grpc-perl#2]
@joyrex2001  Hello I would love to see this module on CPAN.  Do you have a list of tasks that are required to move towards a stable release?  I would like to try and help this effort.

**Comment by joyrex2001** [comment]
I think the code is actually completed. My main concern was that it core-dumps when you connect to a port for which the connection is refused, but turned out to be an issue in the core grpc library instead (https://github.com/grpc/grpc/pull/8205).
 
However, to use grpc, you should also have a protobuf implementation (minimum proto2). I couldn't find one, and hacked https://github.com/joyrex2001/protobuf-perlxs instead. I think this could be much more user-friendly, allthough it works. Maybe there is a better alternative that can be used?

**Comment by slanning** [comment]
http://search.cpan.org/dist/Google-ProtocolBuffers-Dynamic/  ?

**Comment by hexfusion** [comment]
@slanning thanks this looks interesting, really appreciate you note are you interested in helping create a POC?  @joyrex2001 if we can get this going would you consider releasing to CPAN?

**Comment by joyrex2001** [comment]
Yes, that makes sense. There is a gap that needs to be addressed here, the cpan module only implementes the 'message' types. To make it 'rpc', the service type needs to be implemented as well. Typically, this piece is generated by a code generator. If that component is there as well; creating modules for each service, and using the Google-ProtocolBuffers-Dynamic for the 'message' types, we could end up with something more friendly/useable.

**Comment by mbarbon** [comment]
I have a work-in-progress branch to add support for services to Google::ProtocolBuffers::Dynamic: https://github.com/mbarbon/google-protobuf-dynamic/tree/grpc

I tested it with the helloworld service so far, and it works fine.

**Comment by hexfusion** [comment]
@mbarbon thank you for work here very exciting.

**Comment by joyrex2001** [comment]
@mbarbon that's great news, very exciting!

**Comment by mbarbon** [comment]
I uploaded version 0.19 of Google::ProtocolBuffers::Dynamic with support for gRPC client generation.

Do you see other blockers with releasing Grpc::XS to CPAN?

**Comment by joyrex2001** [comment]
No, I don't see any blockers; I need a bit of time to do this though (holiday).

**Comment by joyrex2001** [comment]
Closing issue, as this has been released to cpan: https://metacpan.org/pod/Grpc::XS

**Comment by hexfusion** [comment]
@joyrex2001 @mbarbon thank you!
